import type { GlossaryEntry, DigestNode } from '../digest/schema';
import { expandQueryTerms } from '../digest/expand.ts';
import { tokenize } from './chunk.ts';
import type { Chunk } from './chunk';

export interface Candidate {
  id: string;
  docTitle: string;
  group?: string;
  heading?: string;
  snippet: string;
}

/** Grammatical/generic words that carry no topical signal in a docs query. */
const STOPWORDS = new Set<string>([
  'the', 'a', 'an', 'and', 'or', 'but', 'of', 'to', 'in', 'on', 'at', 'by', 'for', 'with', 'from', 'into', 'as',
  'is', 'are', 'be', 'was', 'were', 'been', 'being', 'do', 'does', 'did', 'how', 'what', 'when', 'where', 'which',
  'who', 'whom', 'why', 'can', 'could', 'should', 'would', 'shall', 'may', 'might', 'my', 'your', 'yours', 'you',
  'i', 'it', 'its', 'this', 'that', 'these', 'those', 'there', 'here', 'we', 'our', 'us', 'me', 'if', 'then',
  'else', 'not', 'no', 'so', 'than', 'too', 'very', 'just', 'also', 'only', 'out', 'about', 'up', 'set', 'get',
  'use', 'using', 'used', 'via', 'want', 'need', 'make', 'have', 'has', 'will',
]);

/**
 * Distinctive tokens the digest carries for a section: its `terms`, the
 * tokens of its distilled `summary`, and the tokens of its verbatim `facts`. A
 * query term hitting any of these means the digest considers that section central
 * to the term, so it earns a ranking boost over an incidental body mention.
 */
function nodeSignal(nodes: DigestNode[] | undefined): Map<string, Set<string>> {
  const signal = new Map<string, Set<string>>();
  if (!nodes) return signal;
  for (const node of nodes) {
    const tokens = new Set<string>(node.terms);
    for (const token of tokenize(node.summary)) tokens.add(token);
    for (const fact of node.facts) for (const token of tokenize(fact.literal)) tokens.add(token);
    signal.set(node.id, tokens);
  }
  return signal;
}

/**
 * Keyword prefilter over heading chunks. Query terms are widened through the
 * digest glossary, scored by token overlap — boosted by the digest's
 * distilled per-section signal when `nodes` are present — then capped per
 * document so one page cannot crowd out the rest of the result set. With no
 * nodes it degrades to plain token overlap over the raw chunk text.
 */
export function prefilter(
  chunks: Chunk[],
  query: string,
  glossary: GlossaryEntry[],
  pool: number,
  perDocCap: number,
  nodes?: DigestNode[],
): Candidate[] {
  const expanded = expandQueryTerms(query, glossary);
  if (!expanded.length) return [];
  // Drop grammatical/generic stopwords so a few ubiquitous words ("how", "set
  // up", "with") don't dominate ranking. Fall back to the raw terms if the query
  // is nothing but stopwords.
  const filtered = expanded.filter((term) => term.length > 1 && !STOPWORDS.has(term));
  const terms = filtered.length ? filtered : expanded;

  const signal = nodeSignal(nodes);
  // Inverse document frequency: down-weight terms common across the corpus
  // (ubiquitous words like "authentication") so a rare, on-topic term ("oidc")
  // dominates. Without it, plain overlap buries the specific section under pages
  // that merely share several common words — which degrades as the corpus grows.
  const df = new Map<string, number>();
  let lengthSum = 0;
  for (const chunk of chunks) {
    lengthSum += chunk.tokens.size;
    for (const token of chunk.tokens) df.set(token, (df.get(token) ?? 0) + 1);
  }
  const total = chunks.length;
  const avgLen = total ? lengthSum / total : 1;
  const weights = new Map(terms.map((term) => [term, Math.log(1 + total / (1 + (df.get(term) ?? 0)))]));
  const b = 0.75; // BM25 length-normalization strength

  const scored = chunks
    .map((chunk) => {
      const boost = signal.get(chunk.id);
      let raw = 0;
      for (const term of terms) {
        const weight = weights.get(term) ?? 0;
        if (chunk.tokens.has(term)) raw += weight;
        if (boost?.has(term)) raw += weight;
      }
      // Length-penalize (not -reward): a huge page (e.g. an autogenerated CLI flag
      // dump that mentions nearly every term) is divided down, but short sections
      // are not boosted — the floor at 1 avoids over-rewarding tiny reference stubs.
      const norm = Math.max(1, 1 - b + (b * chunk.tokens.size) / (avgLen || 1));
      return { chunk, score: raw / norm };
    })
    .filter((candidate) => candidate.score > 0)
    .sort((a, b2) => b2.score - a.score || a.chunk.id.localeCompare(b2.chunk.id));

  const perDoc = new Map<string, number>();
  const capped = [];
  for (const item of scored) {
    const count = perDoc.get(item.chunk.docSlug) ?? 0;
    if (count >= perDocCap) continue;
    perDoc.set(item.chunk.docSlug, count + 1);
    capped.push(item);
    if (capped.length >= pool) break;
  }

  return capped.map(({ chunk }) => ({
    id: chunk.id,
    docTitle: chunk.docTitle,
    group: chunk.group,
    heading: chunk.heading,
    snippet: excerpt(chunk.text, terms),
  }));
}

function excerpt(text: string, terms: string[], radius = 200): string {
  const lower = text.toLowerCase();
  let pos = -1;
  for (const term of terms) {
    const i = lower.indexOf(term);
    if (i !== -1 && (pos === -1 || i < pos)) pos = i;
  }
  const start = pos === -1 ? 0 : Math.max(0, pos - 40);
  const slice = text.slice(start, start + radius).replace(/\s+/g, ' ').trim();
  return (start > 0 ? '...' : '') + slice + (start + radius < text.length ? '...' : '');
}
